### ISSUE TITLE
[Feature]: 请问#3中关于量化部分算子的适配还需要多久？

### ISSUE THREAD

**Issue by Shenggao190** [wangshuai09/vllm#5]
### 🚀 The feature, motivation and pitch

目前需要在npu上使用vllm对量化后的多模态大模型进行加速，希望可以了解这一方面的适配进度！

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by wangshuai09** [comment]
这项工作还没有开启
